cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'node'
brew 'python'
brew 'python3'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'youtube-dl'

cask 'battle-net'
cask 'calibre'
cask 'curse'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'jdiskreport'
cask 'jump-desktop'
cask 'keka'
cask 'musicbrainz-picard'
cask 'steam'
cask 'sublime-text'
cask 'teamviewer'
cask 'transmission'
