#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# If we're on a Mac, let's install homebrew Bundle.
if [ "$(uname -s)" == "Darwin" ]
then
  # Run Homebrew through the Brewfile
  echo "› brew bundle"
  brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
